### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by DefJia** [DefJia/Auto_Reservation_System_BE#3]
Traceback (most recent call last):
  File "_Book_seat.py", line 18, in <module>
    book = Book(target_users[i])
  File "/home/pi/_Codes/Library_seat/Book.py", line 30, in __init__
    self.login()
  File "/home/pi/_Codes/Library_seat/Book.py", line 47, in login
    login_url3 = self.init_url + soup.find('script').text[14:85]
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by DefJia** [comment]
异常处理，待修复
