### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by DefJia** [DefJia/Auto_Reservation_System_BE#4]
Traceback (most recent call last):
  File "_Auto_book.py", line 28, in <module>
    flag = b.book()
  File "/home/pi/_Codes/Library_seat/Book.py", line 85, in book
    available = self.check_available()
  File "/home/pi/_Codes/Library_seat/Book.py", line 114, in check_available
    cur = CheckAvailable(self.username)
  File "/home/pi/_Codes/Library_seat/Advanced/Available.py", line 11, in __init__
    self.info = self.get_info()
  File "/home/pi/_Codes/Library_seat/Advanced/Available.py", line 21, in get_info
    info['status'] = int(is_avai[0])
IndexError: list index out of range

**Comment by DefJia** [comment]
已修复
